// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate envgen gen -c ../tags.yaml -o tags.generated -t ../../../templates/go-env

package tags

// App Application settings with various env tags
type App struct {
	ConfigPath string `env:"APP_CONFIG_PATH,required,file"` // Path to config file
	ApiKey string `env:"APP_API_KEY,required,unset,notEmpty"` // API key that will be unset after reading
	Tags []string `env:"APP_TAGS" envSeparator:";"` // List of tags with custom separator
	Labels map[string]string `env:"APP_LABELS" envSeparator:";" envKeyValSeparator:"="` // Key-value labels with custom separators
}
