linters:
  enable-all: true
  disable:
    # deprecated
    - tenv

    - wrapcheck
    - varnamelen
    - err113

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: github.com/pkg/errors

  exhaustruct:
    exclude:
      - "^github.com/spf13/cobra.Command$"

  
  revive:
    rules:
      - name: var-naming
        arguments:
          - [ ] # AllowList
          - [ ]  # DenyList
          - - skipPackageNameChecks: true

issues:
  exclude:
    - "ST1003: should not use underscores in package names"
    
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - dupl
        - exhaustruct
        - funlen
        - lll
    - path: "templates_tests/template_test\\.go"
      linters:
        - maintidx
    - path: "cmd/envgen/main\\.go"
      linters:
        - lll
        - gochecknoglobals
        - forbidigo
        - gochecknoinits
    - path: "commands/.+\\.go"
      linters:
        - gochecknoglobals
        - forbidigo
