# Generated by envgen. DO NOT EDIT.
# This file was automatically generated and should not be modified manually.

# --------------------------------
# Postgres
# PostgreSQL database settings
# --------------------------------

# Database host
PG_HOST=localhost

# Database port
PG_PORT=5432

# Database user (required)
PG_USER=

# Database password (required)
PG_PASSWORD=

# Database name (required)
PG_DBNAME=

# --------------------------------
# Redis
# Redis cache settings
# --------------------------------

# Redis host
REDIS_HOST=localhost

# Redis port
REDIS_PORT=6379

# Redis password
REDIS_PASSWORD=

# Redis database number
REDIS_DB=0