// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

// Generate configuration
//go:generate envgen gen -c ../meta.yaml -o config.generated -t ../../../templates/go-env
// Generate documentation
//go:generate envgen gen -c ../meta.yaml -o docs/README.md -t ../../../templates/markdown

package meta

// Server Server settings
type Server struct {
	Port int `env:"SERVER_PORT,required" envDefault:"8080"` // Server port
	ENV string `env:"SERVER_ENV,required" envDefault:"development"` // Environment (Possible values: development, staging, production)
}
