// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate envgen -c ../meta_only.yaml -o config.generated -t ../../../templates/go-env
// Config path: ../meta_only.yaml
// Output path: config.generated
// Template path: ../../../templates/go-env
// Generated by: envgen


package config

// ServerConfig represents Server settings
type ServerConfig struct {
	Port int `env:"SERVER_PORT,required" envDefault:"8080"` // Server port
	Env string `env:"SERVER_ENV,required" envDefault:"development"` // Environment (Possible values: development, staging, production)
}