// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate envgen gen -c ../options.yaml -o options.generated -t ../../../templates/go-env

package config

// CustomAppConfig Application settings
type CustomAppConfig struct {
	IsDebug bool `env:"DEBUG_MODE" envDefault:"false"` // Enable debug mode
	Port int `env:"SERVER_PORT,required"` // Server port
}

// DatabaseConfig Database settings
type DatabaseConfig struct {
	URL string `env:"CONNECTION_STRING,required"` // Database connection string
}