// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate envgen gen -c ../basic.yaml -o basic.generated -t ../../../templates/go-env

package config

// AppConfig Basic application settings
type AppConfig struct {
	Debug bool `env:"DEBUG" envDefault:"false"` // Enable debug mode
	Port int `env:"PORT,required"` // Server port
	Host string `env:"HOST" envDefault:"localhost"` // Server host
	mode string `env:"MODE,required" envDefault:"private"` 
}

// DatabaseConfig Database connection settings
type DatabaseConfig struct {
	URL string `env:"DB_URL,required"` // Database connection URL
	LogLevel string `env:"DB_LOG_LEVEL" envDefault:"info"` // Database logging level (Possible values: debug, info, warn, error)
}
