// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate go run github.com/safeblock-dev/envgen/cmd/envgen -c minimal.yaml -o minimal.generated -t ../../templates/go-env

package minimal

// MinimalConfig represents Minimal group with one field
type MinimalConfig struct {
	Value string `env:"VALUE"` // A single value
}