// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package empty_meta

// ServerConfig Server settings
type ServerConfig struct {
	Port int `env:"SERVER_PORT,required" envDefault:"8080"` // Server port
	Env string `env:"SERVER_ENV,required" envDefault:"development"` // Environment (Possible values: development, staging, production)
}