// Code generated by envgen. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

//go:generate envgen gen -c ../../ignore.yaml -o types.generated -t ../../../../templates/go-env

package config
import (
	"time"
)

// App Application settings
type App struct {
	ENV string `env:"ENV,required"` // Application environment (Possible values: development, staging, production)
	Timeout time.Duration `env:"TIMEOUT" envDefault:"30s"` // Operation timeout
}

// DatabaseConfig Database settings
type DatabaseConfig struct {
	Host string `env:"DB_HOST" envDefault:"localhost"` // Database host
	Port int `env:"DB_PORT" envDefault:"5432"` // Database port
}
